// I wish we could use reflection to get all the icons from CupertinoIcons, sadly
// dart:mirrors is not supported in flutter anymore see https://github.com/flutter/flutter/issues/1150
// and this is not feasible with the current version of reflectable https://github.com/google/reflectable.dart
// in the meantime the easiest is to have the list all all the icons
// with some selection kunfu we can easily build the list from https://api.flutter.dev/flutter/cupertino/CupertinoIcons-class.html
import 'package:flutter/cupertino.dart';

class IconRowData {
  const IconRowData(this.name, this.icon);
  final IconData icon;
  final String name;

  static List<IconRowData> get allIcons {
    return const [
      IconRowData('left_chevron', CupertinoIcons.left_chevron),
      IconRowData('right_chevron', CupertinoIcons.right_chevron),
      IconRowData('share', CupertinoIcons.share),
      IconRowData('share_solid', CupertinoIcons.share_solid),
      IconRowData('book', CupertinoIcons.book),
      IconRowData('book_solid', CupertinoIcons.book_solid),
      IconRowData('bookmark', CupertinoIcons.bookmark),
      IconRowData('bookmark_solid', CupertinoIcons.bookmark_solid),
      IconRowData('info', CupertinoIcons.info),
      IconRowData('reply', CupertinoIcons.reply),
      IconRowData('conversation_bubble', CupertinoIcons.conversation_bubble),
      IconRowData('profile_circled', CupertinoIcons.profile_circled),
      IconRowData('plus_circled', CupertinoIcons.plus_circled),
      IconRowData('minus_circled', CupertinoIcons.minus_circled),
      IconRowData('flag', CupertinoIcons.flag),
      IconRowData('search', CupertinoIcons.search),
      IconRowData('check_mark', CupertinoIcons.check_mark),
      IconRowData('check_mark_circled', CupertinoIcons.check_mark_circled),
      IconRowData(
          'check_mark_circled_solid', CupertinoIcons.check_mark_circled_solid),
      IconRowData('circle', CupertinoIcons.circle),
      IconRowData('circle_filled', CupertinoIcons.circle_filled),
      IconRowData('back', CupertinoIcons.back),
      IconRowData('forward', CupertinoIcons.forward),
      IconRowData('home', CupertinoIcons.home),
      IconRowData('shopping_cart', CupertinoIcons.shopping_cart),
      IconRowData('ellipsis', CupertinoIcons.ellipsis),
      IconRowData('phone', CupertinoIcons.phone),
      IconRowData('phone_solid', CupertinoIcons.phone_solid),
      IconRowData('down_arrow', CupertinoIcons.down_arrow),
      IconRowData('up_arrow', CupertinoIcons.up_arrow),
      IconRowData('battery_charging', CupertinoIcons.battery_charging),
      IconRowData('battery_empty', CupertinoIcons.battery_empty),
      IconRowData('battery_full', CupertinoIcons.battery_full),
      IconRowData('battery_75_percent', CupertinoIcons.battery_75_percent),
      IconRowData('battery_25_percent', CupertinoIcons.battery_25_percent),
      IconRowData('bluetooth', CupertinoIcons.bluetooth),
      IconRowData('restart', CupertinoIcons.restart),
      IconRowData('reply_all', CupertinoIcons.reply_all),
      IconRowData('reply_thick_solid', CupertinoIcons.reply_thick_solid),
      IconRowData('share_up', CupertinoIcons.share_up),
      IconRowData('shuffle', CupertinoIcons.shuffle),
      IconRowData('shuffle_medium', CupertinoIcons.shuffle_medium),
      IconRowData('shuffle_thick', CupertinoIcons.shuffle_thick),
      IconRowData('photo_camera', CupertinoIcons.photo_camera),
      IconRowData('photo_camera_solid', CupertinoIcons.photo_camera_solid),
      IconRowData('video_camera', CupertinoIcons.video_camera),
      IconRowData('video_camera_solid', CupertinoIcons.video_camera_solid),
      IconRowData('switch_camera', CupertinoIcons.switch_camera),
      IconRowData('switch_camera_solid', CupertinoIcons.switch_camera_solid),
      IconRowData('collections', CupertinoIcons.collections),
      IconRowData('collections_solid', CupertinoIcons.collections_solid),
      IconRowData('folder', CupertinoIcons.folder),
      IconRowData('folder_solid', CupertinoIcons.folder_solid),
      IconRowData('folder_open', CupertinoIcons.folder_open),
      IconRowData('delete', CupertinoIcons.delete),
      IconRowData('delete_solid', CupertinoIcons.delete_solid),
      IconRowData('delete_simple', CupertinoIcons.delete_simple),
      IconRowData('pen', CupertinoIcons.pen),
      IconRowData('pencil', CupertinoIcons.pencil),
      IconRowData('create', CupertinoIcons.create),
      IconRowData('create_solid', CupertinoIcons.create_solid),
      IconRowData('refresh', CupertinoIcons.refresh),
      IconRowData('refresh_circled', CupertinoIcons.refresh_circled),
      IconRowData(
          'refresh_circled_solid', CupertinoIcons.refresh_circled_solid),
      IconRowData('refresh_thin', CupertinoIcons.refresh_thin),
      IconRowData('refresh_thick', CupertinoIcons.refresh_thick),
      IconRowData('refresh_bold', CupertinoIcons.refresh_bold),
      IconRowData('clear_thick', CupertinoIcons.clear_thick),
      IconRowData('clear_thick_circled', CupertinoIcons.clear_thick_circled),
      IconRowData('clear', CupertinoIcons.clear),
      IconRowData('clear_circled', CupertinoIcons.clear_circled),
      IconRowData('clear_circled_solid', CupertinoIcons.clear_circled_solid),
      IconRowData('add', CupertinoIcons.add),
      IconRowData('add_circled', CupertinoIcons.add_circled),
      IconRowData('add_circled_solid', CupertinoIcons.add_circled_solid),
      IconRowData('gear', CupertinoIcons.gear),
      IconRowData('gear_solid', CupertinoIcons.gear_solid),
      IconRowData('gear_big', CupertinoIcons.gear_big),
      IconRowData('settings', CupertinoIcons.settings),
      IconRowData('settings_solid', CupertinoIcons.settings_solid),
      IconRowData('music_note', CupertinoIcons.music_note),
      IconRowData('double_music_note', CupertinoIcons.double_music_note),
      IconRowData('play_arrow', CupertinoIcons.play_arrow),
      IconRowData('play_arrow_solid', CupertinoIcons.play_arrow_solid),
      IconRowData('pause', CupertinoIcons.pause),
      IconRowData('pause_solid', CupertinoIcons.pause_solid),
      IconRowData('loop', CupertinoIcons.loop),
      IconRowData('loop_thick', CupertinoIcons.loop_thick),
      IconRowData('volume_down', CupertinoIcons.volume_down),
      IconRowData('volume_mute', CupertinoIcons.volume_mute),
      IconRowData('volume_off', CupertinoIcons.volume_off),
      IconRowData('volume_up', CupertinoIcons.volume_up),
      IconRowData('fullscreen', CupertinoIcons.fullscreen),
      IconRowData('fullscreen_exit', CupertinoIcons.fullscreen_exit),
      IconRowData('mic_off', CupertinoIcons.mic_off),
      IconRowData('mic', CupertinoIcons.mic),
      IconRowData('mic_solid', CupertinoIcons.mic_solid),
      IconRowData('clock', CupertinoIcons.clock),
      IconRowData('clock_solid', CupertinoIcons.clock_solid),
      IconRowData('time', CupertinoIcons.time),
      IconRowData('time_solid', CupertinoIcons.time_solid),
      IconRowData('padlock', CupertinoIcons.padlock),
      IconRowData('padlock_solid', CupertinoIcons.padlock_solid),
      IconRowData('eye', CupertinoIcons.eye),
      IconRowData('eye_solid', CupertinoIcons.eye_solid),
      IconRowData('person', CupertinoIcons.person),
      IconRowData('person_solid', CupertinoIcons.person_solid),
      IconRowData('person_add', CupertinoIcons.person_add),
      IconRowData('person_add_solid', CupertinoIcons.person_add_solid),
      IconRowData('group', CupertinoIcons.group),
      IconRowData('group_solid', CupertinoIcons.group_solid),
      IconRowData('mail', CupertinoIcons.mail),
      IconRowData('mail_solid', CupertinoIcons.mail_solid),
      IconRowData('location', CupertinoIcons.location),
      IconRowData('location_solid', CupertinoIcons.location_solid),
      IconRowData('tag', CupertinoIcons.tag),
      IconRowData('tag_solid', CupertinoIcons.tag_solid),
      IconRowData('tags', CupertinoIcons.tags),
      IconRowData('tags_solid', CupertinoIcons.tags_solid),
      IconRowData('bus', CupertinoIcons.bus),
      IconRowData('car', CupertinoIcons.car),
      IconRowData('car_detailed', CupertinoIcons.car_detailed),
      IconRowData('train_style_one', CupertinoIcons.train_style_one),
      IconRowData('train_style_two', CupertinoIcons.train_style_two),
      IconRowData('paw', CupertinoIcons.paw),
      IconRowData('paw_solid', CupertinoIcons.paw_solid),
      IconRowData('game_controller', CupertinoIcons.game_controller),
      IconRowData(
          'game_controller_solid', CupertinoIcons.game_controller_solid),
      IconRowData('lab_flask', CupertinoIcons.lab_flask),
      IconRowData('lab_flask_solid', CupertinoIcons.lab_flask_solid),
      IconRowData('heart', CupertinoIcons.heart),
      IconRowData('heart_solid', CupertinoIcons.heart_solid),
      IconRowData('bell', CupertinoIcons.bell),
      IconRowData('bell_solid', CupertinoIcons.bell_solid),
      IconRowData('news', CupertinoIcons.news),
      IconRowData('news_solid', CupertinoIcons.news_solid),
      IconRowData('brightness', CupertinoIcons.brightness),
      IconRowData('brightness_solid', CupertinoIcons.brightness_solid),
    ];
  }
}
